### ISSUE TITLE
Style Images in Gallery

### ISSUE THREAD

**Issue by hzariman** [cse110-sp21-group18/cse110-sp21-group18#15]
**Briefly describe the required task**
- Style the images that will be added to the Gallery section in Index.html
- Make Gallery Display dynamic, changing layout depending on window size.

**Briefly describe how the solution might be implemented**
- Likely implement the CSS styles into the newly added html elements.

**Comment by dquangucsd** [comment]
I resized the images to fit and had them automatically resize. Pushed to edit.
