### ISSUE TITLE
Redirect to home page from links at the top

### ISSUE THREAD

**Issue by mchera24** [cse110-sp21-group18/cse110-sp21-group18#35]
**Briefly describe the required task**
- When a user clicks the logo, team name, upload picture, or view/edit gallery, you are redirected to the home page.

**Briefly describe how the solution might be implemented**
- event listeners for each and changing the url
- I fixed the data sent from home page to edit page due to the #.

**Comment by hzariman** [comment]
Developed by Manny:
- Used anchor tags for navigation bar links and logo to redirect user to home page.
- Code reviewed as a team over the weekend.
