### ISSUE TITLE
Fix edit page feature grid sizing, especially for larger images

### ISSUE THREAD

**Issue by mchera24** [cse110-sp21-group18/cse110-sp21-group18#37]
**Briefly describe the required task**
-  Fix the edit page feature grid sizing for larger images using css

**Briefly describe how the solution might be implemented**
- responsiveness and other edits to the css file

**Comment by hzariman** [comment]
Resolved by Danny:
- Altered max-width and height CSS attributes for better responsiveness in larger screens
